---
title: "Pea_annotation"
output: html_document
---

Script for proteomic data annotation, mirror plots, heatmap, clustering
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(ggplot2)
library(vegan)
#library("ggfortify")
library(preprocessCore)
library(pheatmap)
library(RColorBrewer)
library(gplots)
library(GGally)
library(limma)
library(factoextra)
library(dplyr)
library(stringr)

```


```{r}
merc_pea <- read.delim("C:/Users/admin/", header = T, sep = "\t")
merc_pea <- subset(merc_pea,!(merc_pea$TYPE==""))

merc_pea$IDENTIFIER <- gsub(merc_pea$IDENTIFIER, pattern = "^.", replacement = "")
merc_pea$IDENTIFIER <- gsub(merc_pea$IDENTIFIER, pattern = ".$", replacement = "")
merc_pea$BINCODE <- gsub(merc_pea$BINCODE, pattern = "^.", replacement = "")
merc_pea$BINCODE <- gsub(merc_pea$BINCODE, pattern = ".$", replacement = "")
merc_pea$BINCODE_global <- merc_pea$BINCODE
merc_pea$BINCODE_global  <- gsub(merc_pea$BINCODE_global, pattern = "\\..*", replacement = "")
```

```{r}
pea_table$ID <- gsub(pea_table$Description, pattern = " .*", replacement = "")
pea_table$ID <- tolower(pea_table$ID)

bin_test <- inner_join(pea_table, merc_pea, by = c("ID" = "IDENTIFIER"))
pea_table <- bin_test
```

```{r mercator 2}
merc_pea_2 <- read.delim("C:/Users/admin/", header = T, sep = "\t")
merc_pea_2 <- subset(merc_pea_2,!(merc_pea_2$TYPE==""))

merc_pea_2$IDENTIFIER <- gsub(merc_pea_2$IDENTIFIER, pattern = "^.", replacement = "")
merc_pea_2$IDENTIFIER <- gsub(merc_pea_2$IDENTIFIER, pattern = ".$", replacement = "")
merc_pea_2$BINCODE <- gsub(merc_pea_2$BINCODE, pattern = "^.", replacement = "")
merc_pea_2$BINCODE <- gsub(merc_pea_2$BINCODE, pattern = ".$", replacement = "")
merc_pea_2$BINCODE_global <- merc_pea_2$BINCODE
merc_pea_2$BINCODE_global  <- gsub(merc_pea_2$BINCODE_global, pattern = "\\..*", replacement = "")
```

```{r}
bin_test <- inner_join(pea_table, merc_pea_2, by = c("ID" = "IDENTIFIER"))
pea_table <- bin_test
```


```{r}
blast_koala_pea <- read.delim("C:/Users/admin/", header = F, sep = "\t")
blast_koala_pea_add <- read.delim("C:/Users/admin/", header = F, sep = "\t")

blast_koala_pea_add$V5 <- gsub(blast_koala_pea_add$V5, pattern = "^$", replacement = NA)
blast_koala_pea_add$V2 <- gsub(blast_koala_pea_add$V2, pattern = "^$", replacement = NA)
blast_koala_pea_add$V2[is.na(blast_koala_pea_add$V2)] <- blast_koala_pea_add$V5[is.na(blast_koala_pea_add$V2)]

blast_koala_pea$full <- blast_koala_pea_add$V2
blast_koala_pea <- blast_koala_pea[, c(1,3)]

blast_koala_pea <- subset(blast_koala_pea,!(blast_koala_pea$full==""))
```

```{r}
names(blast_koala_pea) <- c("IDENTIFIER", "KO")
blast_koala_pea$IDENTIFIER <- tolower(blast_koala_pea$IDENTIFIER)

test_blast <- inner_join(pea_table, blast_koala_pea, by = c("ID" = "IDENTIFIER"))
pea_table <- test_blast
```

```{r}
ngloc_pea <- read.delim("C:/Users/admin/", header = T, sep = "\t")
ngloc_pea <- ngloc_pea[, c(1:3,5,7)]
ngloc_pea$Sequence_ID <- tolower(ngloc_pea$Sequence_ID)

test_blast <- inner_join(pea_table, ngloc_pea, by = c("ID" = "Sequence_ID"))
pea_table <- test_blast
```

```{r}
mean_condition_wild <- subset(pea_table, subset = pea_table$Highest.mean.condition == "wild")
mean_condition_cult <- subset(pea_table, subset = pea_table$Highest.mean.condition == "culture")

loc_wild <- as.data.frame(table(str_split_fixed(mean_condition_wild$Prediction,pattern = ";",n=Inf)))
loc_cult <- as.data.frame(table(str_split_fixed(mean_condition_cult$Prediction,pattern = ";",n=Inf)))
```



######### mirror plots ##############
```{r Mercator 1}
mean_condition_wild$BINCODE_global.x <- paste0(";", mean_condition_wild$BINCODE_global.x)
mean_condition_wild$BINCODE_global.x <- gsub(mean_condition_wild$BINCODE_global.x, pattern = ";", replacement = ";bin")
mean_condition_wild$BINCODE_global.x <- gsub(mean_condition_wild$BINCODE_global.x, pattern = "^;", replacement = "")

mean_condition_cult$BINCODE_global.x <- paste0(";", mean_condition_cult$BINCODE_global.x)
mean_condition_cult$BINCODE_global.x <- gsub(mean_condition_cult$BINCODE_global.x, pattern = ";", replacement = ";bin")
mean_condition_cult$BINCODE_global.x <- gsub(mean_condition_cult$BINCODE_global.x, pattern = "^;", replacement = "")

bin_wild <- as.data.frame(table(str_split_fixed(mean_condition_wild$BINCODE_global.x, pattern = ";",n=Inf)))
bin_cult <- as.data.frame(table(str_split_fixed(mean_condition_cult$BINCODE_global.x, pattern = ";",n=Inf)))
```

```{r Mercator 2}
mean_condition_wild$BINCODE_global.y <- paste0(";", mean_condition_wild$BINCODE_global.y)
mean_condition_wild$BINCODE_global.y <- gsub(mean_condition_wild$BINCODE_global.y, pattern = ";", replacement = ";bin")
mean_condition_wild$BINCODE_global.y <- gsub(mean_condition_wild$BINCODE_global.y, pattern = "^;", replacement = "")

mean_condition_cult$BINCODE_global.y <- paste0(";", mean_condition_cult$BINCODE_global.y)
mean_condition_cult$BINCODE_global.y <- gsub(mean_condition_cult$BINCODE_global.y, pattern = ";", replacement = ";bin")
mean_condition_cult$BINCODE_global.y <- gsub(mean_condition_cult$BINCODE_global.y, pattern = "^;", replacement = "")

bin_wild2 <- as.data.frame(table(str_split_fixed(mean_condition_wild$BINCODE_global.y, pattern = ";",n=Inf)))
bin_cult2 <- as.data.frame(table(str_split_fixed(mean_condition_cult$BINCODE_global.y, pattern = ";",n=Inf)))
```


```{r}
culture_frame <- ask01_3[, c(33, 11, 40)]
wild_frame <- ask3_01[, c(33, 11, 40)]

control_frame$Description <- gsub(control_frame$Description, pattern = "OS.*", replacement = "")
exp_frame$Description <- gsub(exp_frame$Description, pattern = "OS.*", replacement = "")
```


####### Cluster analysis ############
```{r echo=FALSE}
pea_table_clust <- read.csv("C:/Users/admin/", header = T, sep = ";", dec = ",")[, -13]

boxplot(pea_table_clust[,12:20],col="skyblue",border = "black",main="No normalization",
        ylab="intensities",xlab="samples")

pea_table_clust[,12:20] <- log2(pea_table_clust[,12:20])
boxplot(pea_table_clust[,12:20],col="skyblue",border = "black",main="Log2 normalization",
        ylab="intensities",xlab="samples")

# pea_table_clust[,12:20] <- normalizeBetweenArrays(pea_table_clust[,12:20])
# boxplot(pea_table_clust[,12:20],col="skyblue",border = "black",main="Limma normalization",
#         ylab="intensities",xlab="samples")

pea_table_clust[,12:20] <- normalizeQuantiles(pea_table_clust[,12:20])
boxplot(pea_table_clust[,12:20],col="skyblue",border = "black",main="Limma normalization",
        ylab="intensities",xlab="samples")
```

```{r}
names(pea_table_clust)[12:15] <- "culture"
names(pea_table_clust)[16:20] <- "wild"

pca_pea <- as.data.frame(t(pea_table_clust[,12:20]))
pca_pea$'Sample type' <- NA
pca_pea$`Sample type` <- colnames(pea_table_clust[,12:20])
pca_pea$`Sample type` <- gsub(pca_pea$`Sample type`, pattern = "\\.\\d$", replacement = "")


pc <- prcomp(pca_pea[, -646], scale. = T)
summary(pc)
# PC1 - 26.15 %
# PC2 - 5.00 %

# fviz_pca_biplot(pc, repel = TRUE,
#                 col.var = "#2E9FDF", # Variables color
#                 col.ind = "#696969"  # Individuals color
#                 )


plot_1 <- ggplot(df_scores, aes(x=PC1,y=PC2,col=pca_pea$`Sample type`))+
  geom_point(size=13,alpha=0.5)+
  theme(axis.text = element_blank(),axis.ticks.x = element_blank())+
  xlab(paste0("Principal component 1: ","26.15 %"))+
  ylab(paste0("Principal component 2: ","5.00 %"))+labs(color='')+ggtitle("Pea_coat_PCA_normalizeQuantiles")
plot_1

```


```{r}
# 'ward.D', 'ward.D2', 'single', 'complete', 'average', 'mcquitty', 'median' or 'centroid'####

pheatmap(as.matrix(pea_table_clust[, 12:20]),
         cluster_cols = T, cluster_rows = T, clustering_distance_rows = "euclidean" ,
         clustering_distance_cols = "correlation" , clustering_method = "average",
         show_rownames = F,
         bluered(75),border_color = NA,
         angle_col = 45)
```

```{r}
pea_table_clust$`culture_mean` <- rowMeans(pea_table_clust[,12:15])
pea_table_clust$`wild_mean` <- rowMeans(pea_table_clust[,16:20])

#pea_table_clust[,21:22] <- log2(pea_table_clust[,21:22])

d <- dist(as.matrix(pea_table_clust[,12:20]),method = "euclidean") 
hc <- hclust(d, method = "average")
cluster <- cutree(hc, 16)
pea_table_clust$cluster <- as.factor(cluster)

ggparcoord(pea_table_clust,columns = 21:22,title = "Culture vs Wild",showPoints = TRUE,scale = "globalminmax")+
  xlab("Sample groups")+ylab("Normalized abundance")+
  theme_bw()+theme(axis.text.x = element_text(angle = 45,hjust = 1))+
  facet_wrap(~pea_table_clust$cluster)

rownames(pea_table_clust) <- pea_table_clust$Accession
annot_row_1 <- pea_table_clust[,c(1,NCOL(pea_table_clust))]

rownames(annot_row_1) = as.character(unlist(annot_row_1[,1]))
annot_row_1 <- annot_row_1[order(annot_row_1$cluster),]
annot_row_1[,1] <- annot_row_1$cluster
annot_row_1$Accession <- NULL


# 'ward.D', 'ward.D2', 'single', 'complete', 'average', 'mcquitty', 'median' or 'centroid'####
pheatmap(pea_table_clust[, 12:20],
         cluster_cols = F, cluster_rows = T, cutree_rows = 1, main = "Pea heatmap",
         clustering_distance_cols = "correlation" , clustering_method = "mcquitty",
         show_rownames = F,angle_col = 45, annotation_row = annot_row_1, bluered(100), border_color = NA)
```

